### ISSUE TITLE
Error Cannot read property length

### ISSUE THREAD

**Issue by davidperezgar** [antoniotorresg/app-chiclana#1]
Buenas Antonio, estoy siguiendo tus indicaciones del pasado taller. 
¿Quería preguntarte si este error porqué se ha debido?

Gracias

Error
Close
Runtime Error
Cannot read property 'length' of undefined
Stack
TypeError: Cannot read property 'length' of undefined
    at WpProvider.webpackJsonp.211.WpProvider.getUserImage (http://localhost:8100/build/main.js:294:51)
    at BlogPage.webpackJsonp.150.BlogPage.getUserImage (http://localhost:8100/build/main.js:36:32)
    at Object.eval [as updateRenderer] (ng:///AppModule/BlogPage.ngfactory.js:47:25)
    at Object.debugUpdateRenderer [as updateRenderer] (http://localhost:8100/build/vendor.js:15041:21)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:14177:14)
    at callViewAction (http://localhost:8100/build/vendor.js:14522:21)
    at execEmbeddedViewsAction (http://localhost:8100/build/vendor.js:14480:17)
    at checkAndUpdateView (http://localhost:8100/build/vendor.js:14173:5)
    at callViewAction (http://localhost:8100/build/vendor.js:14522:21)
    at execComponentViewsAction (http://localhost:8100/build/vendor.js:14454:13)
Ionic Framework: 3.9.2
Ionic App Scripts: 3.1.0
Angular Core: 5.0.0
Angular Compiler CLI: 5.0.0
Node: 6.11.4
OS Platform: macOS High Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

**Comment by davidperezgar** [comment]
¿Cuales eran los plugins necesarios en el WordPress?
